Rearchitect the code so we can print out the actual error

diff --git a/ansible/roles/iib_ci/tasks/mirror-related-images.yml b/ansible/roles/iib_ci/tasks/mirror-related-images.yml
--- a/ansible/roles/iib_ci/tasks/mirror-related-images.yml
+++ b/ansible/roles/iib_ci/tasks/mirror-related-images.yml
@@ -33,13 +33,24 @@
     right=$(grep "{{ image }}" "{{ iib_local_folder }}/mapping.txt" | cut -f2 -d=)
     right_base=$(echo $right | sed -e 's/:.*$//' -e 's/@.*$//')
     right_log=$(echo "${right_base}@${left_sha}" | sed -e 's/\//-/g')
-    if skopeo inspect --authfile "{{ pull_secrets_tempfolder.path }}/.dockerconfigjson" --no-tags docker://"{{ image }}" > /tmp/skopeo-"{{ image | regex_replace('/', '-') }}".log; then
+    left_out=$(skopeo inspect --authfile "{{ pull_secrets_tempfolder.path }}/.dockerconfigjson" --no-tags docker://"{{ image }}" 2>&1)
+    left_ret=$?
+    if [ $left_ret -eq 0 ]; then
       echo "{{ image }}"
-    elif skopeo inspect --authfile "{{ pull_secrets_tempfolder.path }}/.dockerconfigjson" --no-tags docker://"${right_base}@${left_sha}" > "/tmp/skopeo-${right_log}.log"; then
-      echo "${right_base}@${left_sha}"
     else
-      echo "ERROR: both {{ image }} and echo ${right_base}@${left_sha} could not be found"
-      exit 1
+      echo "${left_out}" > /tmp/skopeo-"{{ image | regex_replace('/', '-') }}".log
+      right_out=$(skopeo inspect --authfile "{{ pull_secrets_tempfolder.path }}/.dockerconfigjson" --no-tags docker://"${right_base}@${left_sha}" 2>&1)
+      right_ret=$?
+      if [ $right_ret -eq 0 ]; then
+        echo "${right_base}@${left_sha}"
+      else # both left_ret and right_ret were != 0
+        echo "${right_out}" > "/tmp/skopeo-${right_log}.log"
+        echo "ERROR: both {{ image }} and echo ${right_base}@${left_sha} could not be found"
+        echo "Printing both outputs:"
+        echo "Left out: ${left_out}"
+        echo "Right out: ${right_out}"
+        exit 1
+      fi
     fi
   register: all_existing_images
   with_items: "{{ all_images }}"
